name: JS tests
on: [push, pull_request]
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  js-tests:
    name: JS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run:
          npm install --prefix ./_dev

      - name: Launch typescript linter
        run:
          npm run test --prefix ./_dev
  js-linter:
    name: JS linter syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run:
          npm install --prefix ./_dev

      - name: Launch typescript linter
        run:
          npm run lint --prefix ./_dev

      - name: Launch scss linter
        run:
          npm run lint-scss --prefix ./_dev
